// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
    {"name":"gotocardbattle","status":true,"description":"","parameters":{}},
    {"name":"cardbattle_config","status":true,"description":"","parameters":{}},
    {"name":"cardbattle_manager","status":true,"description":"","parameters":{}},
    {"name":"game_cardplayer","status":true,"description":"","parameters":{}},
    {"name":"scene_cardbattle","status":true,"description":"","parameters":{}},
    {"name":"sprite_background","status":true,"description":"","parameters":{}}
];


